MySQL:
  Host: 'your_database'
  Port: '3306'
  User: 'username'
  Password: 'password'
  Database: 'prismc'
ActionBar:
  1Digit: '&e&l&r [LEVEL]&r [PROGRESS]      '
  2Digit: '&e&l&r [LEVEL]&r [PROGRESS]      '
  3Digit: '&e&l&r [LEVEL]&r [PROGRESS]      '
Filter:
  HIGH:
    - '[EXACT] ass'
    - '[EXACT] hell'
    - '[EXACT] butt'
    - '[EXACT] cock'
    - '[EXACT] cum'
    - '[EXACT] cunt'
    - '[EXACT] nude'
    - '[EXACT] tit'
    - '[STRING] ball gag'
    - '[STRING] ball gravy'
    - '[STRING] ball kicking'
    - '[STRING] ball licking'
    - '[STRING] ball sack'
    - '[STRING] ball sucking'
    - '[STRING] barely legal'
    - '[STRING] big black'
    - '[STRING] big breasts'
    - '[STRING] big knockers'
    - '[STRING] big tits'
    - '[STRING] black cock'
    - '[STRING] fuck buttons'
    - '[STRING] fudge packer'
    - '[STRING] gay sex'
    - '[STRING] giant cock'
    - '[STRING] god damn'
    - '[STRING] jelly donut'
    - '[STRING] make me come'
    - '[STRING] nsfw images'
    - '[STRING] piece of shit'
    - '[STRING] strip club'
    - '[STRING] tea bagging'
    - anus
    - apeshit
    - arsehole
    - asshole
    - babeland
    - barenaked
    - bastard
    - bastardo
    - beaner
    - beaners
    - boner
    - boob
    - busty
    - buttcheeks
    - butthole
    - cocks
    - crap
    - damn
    - escort
    - genitals
    - kinky
    - nsfw
    - nudity
    - panties
    - penis
    - sex
    - shrimping
    - suck
    - tits
    - titties
    - titty
    - wtf
  MEDIUM:
    - '[EXACT] anal'
    - assmunch
    - bimbos
    - bitch
    - bitches
    - blowjob
    - bullshit
    - cumming
    - dick
    - fuck
    - fudgepacker
    - horny
    - humping
    - intercourse
    - jizz
    - juggs
    - masturbate
    - masturbating
    - masturbation
    - milf
    - motherfucker
    - porn
    - porno
    - pornography
    - sexcam
    - sexo
    - sexual
    - sexuality
    - sexually
    - sexy
    - shit
    - shitblimp
    - shitty
    - threesome
    - topless
    - tushy
    - vagina
    - whore
  LOW:
    - '[EXACT] clit'
    - '[EXACT] coon'
    - '[EXACT] fag'
    - '[EXACT] orgy'
    - '[EXACT] poof'
    - '[EXACT] poon'
    - '[EXACT] smut'
    - '[EXACT] wank'
    - '[EXACT] xx'
    - '[EXACT] xxx'
    - '[STRING] 2 girls 1 cup'
    - '[STRING] alabama hot pocket'
    - '[STRING] alaskan pipeline'
    - '[STRING] auto erotic'
    - '[STRING] baby batter'
    - '[STRING] baby juice'
    - '[STRING] beaver cleaver'
    - '[STRING] beaver lips'
    - '[STRING] blonde action'
    - '[STRING] blonde on blonde action'
    - '[STRING] blow job'
    - '[STRING] blow your load'
    - '[STRING] blue waffle'
    - '[STRING] booty call'
    - '[STRING] brown showers'
    - '[STRING] brunette action'
    - '[STRING] bullet vibe'
    - '[STRING] bung hole'
    - '[STRING] camel toe'
    - '[STRING] carpet muncher'
    - '[STRING] chocolate rosebuds'
    - '[STRING] cleveland steamer'
    - '[STRING] clover clamps'
    - '[STRING] date rape'
    - '[STRING] deep throat'
    - '[STRING] dirty pillows'
    - '[STRING] dirty sanchez'
    - '[STRING] dog style'
    - '[STRING] doggie style'
    - '[STRING] doggy style'
    - '[STRING] doggystyle'
    - '[STRING] donkey punch'
    - '[STRING] double dong'
    - '[STRING] double penetration'
    - '[STRING] dp action'
    - '[STRING] dry hump'
    - '[STRING] eat my ass'
    - '[STRING] female squirting'
    - '[STRING] foot fetish'
    - '[STRING] gang bang'
    - '[STRING] girl on top'
    - '[STRING] girl on'
    - '[STRING] girls gone wild'
    - '[STRING] golden shower'
    - '[STRING] goo girl'
    - '[STRING] group sex'
    - '[STRING] hand job'
    - '[STRING] hard core'
    - '[STRING] hot carl'
    - '[STRING] hot chick'
    - '[STRING] how to kill'
    - '[STRING] how to murder'
    - '[STRING] jack off'
    - '[STRING] jail bait'
    - '[STRING] jerk off'
    - '[STRING] leather restraint'
    - '[STRING] leather straight jacket'
    - '[STRING] lemon party'
    - '[STRING] male squirting'
    - '[STRING] menage a trois'
    - '[STRING] missionary position'
    - '[STRING] mound of venus'
    - '[STRING] mr hands'
    - '[STRING] muff diver'
    - '[STRING] nig nog'
    - '[STRING] one cup two girls'
    - '[STRING] one guy one jar'
    - '[STRING] phone sex'
    - '[STRING] piss pig'
    - '[STRING] pleasure chest'
    - '[STRING] pole smoker'
    - '[STRING] poop chute'
    - '[STRING] prince albert piercing'
    - '[STRING] raging boner'
    - '[STRING] reverse cowgirl'
    - '[STRING] rosy palm and her 5 sisters'
    - '[STRING] rosy palm'
    - '[STRING] rusty trombone'
    - '[STRING] shaved beaver'
    - '[STRING] shaved pussy'
    - '[STRING] splooge moose'
    - '[STRING] spooge'
    - '[STRING] spread legs'
    - '[STRING] strap on'
    - '[STRING] style doggy'
    - '[STRING] suck my dick'
    - '[STRING] suicide girls'
    - '[STRING] sultry women'
    - '[STRING] tainted love'
    - '[STRING] taste my'
    - '[STRING] tied up'
    - '[STRING] tight white'
    - '[STRING] tongue in a'
    - '[STRING] tub girl'
    - '[STRING] two girls one cup'
    - '[STRING] urethra play'
    - '[STRING] venus mound'
    - '[STRING] violet wand'
    - '[STRING] wet dream'
    - '[STRING] white power'
    - '[STRING] wrapping men'
    - '[STRING] wrinkled starfish'
    - '[STRING] yellow showers'
    - 2g1c
    - acrotomophilia
    - anilingus
    - autoerotic
    - bangbros
    - bangbus
    - bareback
    - bastinado
    - bbw
    - bdsm
    - beastiality
    - bestiality
    - birdlock
    - blumpkin
    - bollocks
    - bondage
    - bukkake
    - bulldyke
    - bunghole
    - camgirl
    - camslut
    - camwhore
    - carpetmuncher
    - cialis
    - circlejerk
    - clitoris
    - clusterfuck
    - coons
    - coprolagnia
    - coprophilia
    - cornhole
    - creampie
    - cumshot
    - cumshots
    - cunnilingus
    - darkie
    - daterape
    - deepthroat
    - dendrophilia
    - dildo
    - dingleberries
    - dingleberry
    - doggiestyle
    - dolcett
    - domination
    - dominatrix
    - dommes
    - dvda
    - ecchi
    - ejaculation
    - erotic
    - erotism
    - eunuch
    - faggot
    - fecal
    - felch
    - fellatio
    - feltch
    - femdom
    - figging
    - fingerbang
    - fingering
    - fisting
    - footjob
    - frotting
    - futanari
    - g-spot
    - gangbang
    - goatcx
    - goatse
    - gokkun
    - goodpoop
    - goregasm
    - grope
    - gspot
    - guro
    - handjob
    - hardcore
    - hentai
    - homoerotic
    - honkey
    - hooker
    - incest
    - jailbait
    - jigaboo
    - jiggaboo
    - jiggerboo
    - kike
    - kinbaku
    - kinkster
    - knobbing
    - livesex
    - lolita
    - lovemaking
    - mong
    - muffdiving
    - nambla
    - nawashi
    - negro
    - neonazi
    - nigga
    - nigger
    - nimphomania
    - nipple
    - nutten
    - nympho
    - nymphomania
    - octopussy
    - omorashi
    - orgasm
    - paedophile
    - paki
    - panty
    - pedobear
    - pedophile
    - pegging
    - pikey
    - pissing
    - pisspig
    - playboy
    - ponyplay
    - poontang
    - poopchute
    - pthc
    - pubes
    - punany
    - pussy
    - queaf
    - queef
    - quim
    - raghead
    - rape
    - raping
    - rapist
    - rectum
    - rimjob
    - rimming
    - s&m
    - sadism
    - santorum
    - scat
    - schlong
    - scissoring
    - semen
    - shemale
    - shibari
    - shota
    - skeet
    - slanteye
    - slut
    - snatch
    - snowballing
    - sodomize
    - sodomy
    - spastic
    - spic
    - splooge
    - spunk
    - strapon
    - strappado
    - swastika
    - swinger
    - throating
    - thumbzilla
    - tosser
    - towelhead
    - tranny
    - tribadism
    - tubgirl
    - twat
    - twink
    - twinkie
    - undressing
    - upskirt
    - urophilia
    - viagra
    - vibrator
    - vorarephilia
    - voyeur
    - voyeurweb
    - voyuer
    - vulva
    - wetback
    - worldsex
    - yaoi
    - yiffy
    - zoophilia